const orders = [
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005211,
    RequestNumber: 442,
    VIN: "AUTOVIN500066",
    Customer: "HERTZ",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Buickkk",
    BodyType: "Sedan",
    Model: "Regal",
    Weight: null,
    CurbWeight: 3439,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 94,
    DocumentId: 464,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005210,
    RequestNumber: 442,
    VIN: "2T3BF4DV2CW22911",
    Customer: "HERTZ",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T18:19:30.0423617",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2013,
    Make: "Toyota",
    BodyType: "SUV",
    Model: "RAV4",
    Weight: 3863,
    CurbWeight: 3494,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 93,
    DocumentId: 463,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005209,
    RequestNumber: 439,
    VIN: "5YJ3E1EA1PF452511",
    Customer: "HERTZ",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "12345678901254",
    DMVState: "XX",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-02-08T17:07:12.5812543",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2023,
    Make: "Tesla",
    BodyType: "Sedan",
    Model: "Model 3",
    Weight: 565,
    CurbWeight: 3862,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 92,
    DocumentId: 460,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005208,
    RequestNumber: 326,
    VIN: "5YJ3E1EA1PF452511",
    Customer: "13224865",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-26T16:04:20.0251057",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2023,
    Make: "Tesla",
    BodyType: "Sedan",
    Model: "Model 3",
    Weight: null,
    CurbWeight: 3862,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 91,
    DocumentId: 454,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005207,
    RequestNumber: 344,
    VIN: "5YJ3E1EA1PF452511",
    Customer: "13224865",
    Status: "Error",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-26T16:04:20.0251057",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: null,
    Make: null,
    BodyType: null,
    Model: null,
    Weight: null,
    CurbWeight: null,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "UI-PATH",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 2,
    WorkOrderDetailId: 90,
    DocumentId: 453,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 2, Text: "Error", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005206,
    RequestNumber: 371,
    VIN: "5YJ3E1EAXPF453365",
    Customer: "HERTZ",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "12345678901254",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-30T21:35:35.7430782",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: null,
    Make: null,
    BodyType: null,
    Model: null,
    Weight: null,
    CurbWeight: null,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 89,
    DocumentId: 459,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005205,
    RequestNumber: 371,
    VIN: "1N4BL4BVBNN300269",
    Customer: "HERTZ",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "12345678901254",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-30T21:35:35.7430782",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2022,
    Make: "Nissan",
    BodyType: "Sedan",
    Model: "Altima",
    Weight: 3160,
    CurbWeight: 3244,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 88,
    DocumentId: 458,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005204,
    RequestNumber: 346,
    VIN: "1C4SJVFP7PS510562",
    Customer: "HERTZ",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-26T16:26:38.4373204",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2023,
    Make: "Wagoneer",
    BodyType: "SUV",
    Model: "Grand Wagoneer",
    Weight: 6091,
    CurbWeight: 6412,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 87,
    DocumentId: 457,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005203,
    RequestNumber: 261,
    VIN: "5NMS23AD2LH153652",
    Customer: "HERTZ",
    Status: "Error",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA12345",
    DMVState: "FL",
    LienHolder: "BNY MELLON",
    Registrant: "HERTZ REGISTRANT",
    Owner: "HERTZ TITLE OWNER",
    ReceivedDate: "2022-12-27T03:40:30.7775448",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: null,
    Make: null,
    BodyType: null,
    Model: null,
    Weight: null,
    CurbWeight: null,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "PKOTIPALLI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "UI-PATH",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 2,
    WorkOrderDetailId: 86,
    DocumentId: 100,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 2, Text: "Error", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: "E2E testing",
  },
  {
    TransactionId: 1005202,
    RequestNumber: 326,
    VIN: "1N4BL4BVSNN307906",
    Customer: "13224865",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-20T20:56:14.5051242",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2022,
    Make: "Nissan",
    BodyType: "Sedan",
    Model: "Altima",
    Weight: 3160,
    CurbWeight: 3244,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 85,
    DocumentId: 452,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005201,
    RequestNumber: 326,
    VIN: "1C4SJVFP1PS510556",
    Customer: "13224865",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-20T20:56:14.5051242",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2023,
    Make: "Wagoneer",
    BodyType: "SUV",
    Model: "Grand Wagoneer",
    Weight: 0,
    CurbWeight: 6412,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: false,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 84,
    DocumentId: 451,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005200,
    RequestNumber: 408,
    VIN: "5UXTY3C0uututu",
    Customer: "HERTZ",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "123",
    DMVState: "AB",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-20T20:56:14.5051242",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2023,
    Make: "Wagoneer",
    BodyType: "SUV",
    Model: "Grand Wagoneer",
    Weight: 6091,
    CurbWeight: 6412,
    Color: null,
    Color2: null,
    TitleNumber: "title",
    SalesTax: 1.0,
    PlateNumber: null,
    PreviousStateProvinceCode: "AB",
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 83,
    DocumentId: 450,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005199,
    RequestNumber: 383,
    VIN: "5YJ3E1EA1PF452511",
    Customer: "HERTZ",
    Status: "Error",
    TransactionType: "",
    TrackingNumber: "123",
    DMVState: "AK",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-19T05:56:35.2416824",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2023,
    Make: "Tesla",
    BodyType: "Sedan",
    Model: "Model 3",
    Weight: 3863,
    CurbWeight: 3863,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 2,
    WorkOrderDetailId: 82,
    DocumentId: 449,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 2, Text: "Error", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005198,
    RequestNumber: 407,
    VIN: "5YJ3E1EAXPF453365",
    Customer: "HERTZ",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "123",
    DMVState: "AE",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-19T05:56:35.2416824",
    SVRSImportNumber: null,
    SVRSCustomerNumber: "1803",
    ModelYear: 2023,
    Make: "Tesla",
    BodyType: "Sedan",
    Model: "Model 3",
    Weight: 3863,
    CurbWeight: 3862,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "HERTZ",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 81,
    DocumentId: 448,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005197,
    RequestNumber: 324,
    VIN: "1N6AA1ED4MN512238",
    Customer: "13224865",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-19T05:23:44.0462142",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2021,
    Make: "Nissan",
    BodyType: "Pickup",
    Model: "Titan",
    Weight: 5515,
    CurbWeight: 5649,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 80,
    DocumentId: 447,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005196,
    RequestNumber: 324,
    VIN: "1N6ED1EJ7NN607182",
    Customer: "13224865",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-19T05:23:44.0462142",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2022,
    Make: "Nissan",
    BodyType: "Pickup",
    Model: "Frontier",
    Weight: 4352,
    CurbWeight: 4473,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 79,
    DocumentId: 446,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005195,
    RequestNumber: 323,
    VIN: "5YJ3E1EA1PF452511",
    Customer: "13224865",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-19T04:05:52.583698",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2023,
    Make: "Tesla",
    BodyType: "Sedan",
    Model: "Model 3",
    Weight: 3863,
    CurbWeight: 3862,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 78,
    DocumentId: 445,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005194,
    RequestNumber: 323,
    VIN: "5YJ3E1EAXPF453365",
    Customer: "13224865",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-19T04:05:52.583698",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2023,
    Make: "Tesla",
    BodyType: "Sedan",
    Model: "Model 3",
    Weight: 3863,
    CurbWeight: 3862,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 77,
    DocumentId: 444,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005193,
    RequestNumber: 322,
    VIN: "",
    Customer: "13224865",
    Status: "Error",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-18T20:22:23.2632348",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: null,
    Make: null,
    BodyType: null,
    Model: null,
    Weight: null,
    CurbWeight: null,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: null,
    Source: "UI PATH",
    SourceErrorCode: "UIPATH_LOWCONFIDENCE",
    SourceErrorDecsription:
      "Document Extraction ocr confidence is low for few fields hence triggering action center task to validate.",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 2,
    WorkOrderDetailId: null,
    DocumentId: 443,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 2, Text: "Error", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005192,
    RequestNumber: 322,
    VIN: "1C4SJVFP1PS510556",
    Customer: "13224865",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-18T20:22:23.2632348",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2023,
    Make: "Wagoneer",
    BodyType: "SUV",
    Model: "Grand Wagoneer",
    Weight: 6091,
    CurbWeight: 6412,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 76,
    DocumentId: 442,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005191,
    RequestNumber: 321,
    VIN: "1C4SJVFP7PS510562",
    Customer: "13224865",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-18T17:35:59.0590418",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2023,
    Make: "Wagoneer",
    BodyType: "SUV",
    Model: "Grand Wagoneer",
    Weight: 6091,
    CurbWeight: 6412,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 75,
    DocumentId: 441,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005190,
    RequestNumber: 321,
    VIN: "5YJ3E1EA1PF452511",
    Customer: "13224865",
    Status: "Duplicate",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-18T17:35:59.0590418",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2023,
    Make: "Tesla",
    BodyType: "Sedan",
    Model: "Model 3",
    Weight: 3863,
    CurbWeight: 3862,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 4,
    WorkOrderDetailId: 74,
    DocumentId: 440,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 4, Text: "Duplicate", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005189,
    RequestNumber: 321,
    VIN: "5YJ3E1EAXPF453365",
    Customer: "13224865",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-18T17:35:59.0590418",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2023,
    Make: "Tesla",
    BodyType: "Sedan",
    Model: "Model 3",
    Weight: 3863,
    CurbWeight: 3862,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 73,
    DocumentId: 439,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005188,
    RequestNumber: 320,
    VIN: "5YJ3E1EA1PF452511",
    Customer: "13224865",
    Status: "Active",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-17T22:32:13.0660443",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: 2023,
    Make: "Tesla",
    BodyType: "Sedan",
    Model: "Model 3",
    Weight: 3863,
    CurbWeight: 3862,
    Color: null,
    Color2: null,
    TitleNumber: "",
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: "MSO",
    Source: "UI PATH",
    SourceErrorCode: "",
    SourceErrorDecsription: "",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 1,
    WorkOrderDetailId: 72,
    DocumentId: 438,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 1, Text: "Active", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005187,
    RequestNumber: 319,
    VIN: "",
    Customer: "13224865",
    Status: "Error",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-17T22:13:22.2449333",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: null,
    Make: null,
    BodyType: null,
    Model: null,
    Weight: null,
    CurbWeight: null,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: null,
    Source: "UI PATH",
    SourceErrorCode: "UIPATH_ERROR",
    SourceErrorDecsription: "File Format Is Not Supported",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 2,
    WorkOrderDetailId: null,
    DocumentId: 436,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 2, Text: "Error", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005186,
    RequestNumber: 317,
    VIN: "",
    Customer: "13224865",
    Status: "Error",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FM",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-17T21:25:18.0047217",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: null,
    Make: null,
    BodyType: null,
    Model: null,
    Weight: null,
    CurbWeight: null,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: null,
    Source: "UI PATH",
    SourceErrorCode: "UIPATH_ERROR",
    SourceErrorDecsription: "File Format Is Not Supported",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 2,
    WorkOrderDetailId: null,
    DocumentId: 434,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 2, Text: "Error", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005185,
    RequestNumber: 316,
    VIN: "",
    Customer: "13224865",
    Status: "Error",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-17T21:20:43.2374407",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: null,
    Make: null,
    BodyType: null,
    Model: null,
    Weight: null,
    CurbWeight: null,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: null,
    Source: "UI PATH",
    SourceErrorCode: "UIPATH_ERROR",
    SourceErrorDecsription: "File Format Is Not Supported",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 2,
    WorkOrderDetailId: null,
    DocumentId: 432,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 2, Text: "Error", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005184,
    RequestNumber: 315,
    VIN: "",
    Customer: "13224865",
    Status: "Error",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-17T21:08:25.0238512",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: null,
    Make: null,
    BodyType: null,
    Model: null,
    Weight: null,
    CurbWeight: null,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: null,
    Source: "UI PATH",
    SourceErrorCode: "UIPATH_ERROR",
    SourceErrorDecsription: "File Format Is Not Supported",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 2,
    WorkOrderDetailId: null,
    DocumentId: 431,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 2, Text: "Error", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
  {
    TransactionId: 1005183,
    RequestNumber: 314,
    VIN: "",
    Customer: "13224865",
    Status: "Error",
    TransactionType: "",
    TrackingNumber: "DUMMYDATA1234",
    DMVState: "FL",
    LienHolder: null,
    Registrant: null,
    Owner: null,
    ReceivedDate: "2023-01-17T20:50:19.1205891",
    SVRSImportNumber: null,
    SVRSCustomerNumber: null,
    ModelYear: null,
    Make: null,
    BodyType: null,
    Model: null,
    Weight: null,
    CurbWeight: null,
    Color: null,
    Color2: null,
    TitleNumber: null,
    SalesTax: null,
    PlateNumber: null,
    PreviousStateProvinceCode: null,
    CreatedUser: "HMARNENI",
    DocumentType: null,
    Source: "UI PATH",
    SourceErrorCode: "UIPATH_ERROR",
    SourceErrorDecsription: "File Format Is Not Supported",
    SentToSVRS: false,
    SentToWIP: true,
    ClientCode: "13224865",
    TotalRowCount: 1005067,
    TransactionTypeId: null,
    StatusId: 2,
    WorkOrderDetailId: null,
    DocumentId: 430,
    User: null,
    IsWorkOrderDetailEdited: false,
    IsVinEdited: false,
    IsWorkOrderEdited: false,
    IsUpdatedSuccessfully: false,
    IsBulkVinDecodeUpdate: false,
    WorkOrderStatusList: { Value: 2, Text: "Error", Name: null },
    TransactionTypeList: { Value: 0, Text: "", Name: null },
    Comments: null,
  },
];
module.exports = {
  orders
};
